- name: Test Playbook
  hosts: localhost
  vars:
    kube_cpu: 4
    kube_memory: 12g
    kube_disk: 50G
    kube_profile: apmtest
    kube_modules:
      - metrics-server
      #- dashboard
      - registry
      - ingress
      - ingress-dns
  tasks:
    - block:
        - name: Start Kubernetes Test Environment
          command: "minikube start --profile={{ kube_profile }} --disk-size={{ kube_disk }} --cpus={{ kube_cpu }} --memory={{ kube_memory }} --container-runtime=cri-o"
        - name: Enable Addons
          command: "minikube --profile={{ kube_profile }} addons enable {{ item }}"
          with_items:
            - "{{ kube_modules }}"
        - name: Create build directory
          file:
            path: ./tmp_build
            state: directory
        - name: Clone the repository
          ansible.builtin.git:
            repo: https://github.com/yohanswanepoel/ansible_apm_test.git
            dest: ./tmp_build
        - name: Build container
          args:
            chdir: ./tmp_build/python_app/src
          command: minikube --profile apmtest image build -t skaffold-demo .
          register: build_output
        - name: Build output
          debug:
            var: build_output
        - name: Create a k8s namespace
          kubernetes.core.k8s:
            api_version: v1
            kind: Namespace
            name: development
            state: present
        - name: Create a Deployment
          k8s:
            state: present      # State=present when you need to create new object
            namespace: development # defining the namespace
            src: ./tmp_build/python_app/app-local/k8s-app.yaml
            wait: yes
            wait_condition:
              type: Available
              status: True
              reason: MinimumReplicasAvailable
            wait_timeout: 240
        - name: Create a Service
          k8s:
            state: present      # State=present when you need to create new object
            namespace: development # defining the namespace
            src: ./tmp_build/python_app/app-local/k8s-service.yaml 
        - name: Set development namespace context
          command: kubectl config set-context --current --namespace=development
        - name: Get Nodeport IP Address
          command: minikube -p apmtest ip
          register: test_ip
        - name: Get test url
          command: "kubectl get svc skaffold-demo -n development -o go-template='http://{{ test_ip.stdout }}:{{ '{{' }}range.spec.ports{{ '}}' }}{{ '{{' }}if .nodePort{{ '}}' }}{{ '{{' }}.nodePort{{ '}}' }}{{ '{{' }}end{{ '}}' }}{{ '{{' }}end{{ '}}' }}'"
          register: test_url
        - name: Service URL for the Django App
          debug:
            var: test_url.stdout
        - name: Run tests to generate APM traffic
          shell: export TEST_URL={{ test_url.stdout }}; pytest --otel-service-name='{{ lookup('env', 'OTEL_SERVICE_NAME') | default('Account Test Environment', True) }}' --otel-session-name='Account Service Test Cases' ./tmp_build/python_app/test_traffic.py 
        #- name: Get petclinic url
        #  command: "minikube --profile=apmtest service petclinic -n development"
        #  register: petclinic_url
        #- name: Display number of Services in the myapp namespace.
        #  debug:
        #    var: petclinic_url

      #rescue:
      #  - name: delete Minikube
      #    command: "minikube delete --profile={{ kube_profile }}"
      always:
        - name: Delete content & directory
          file:
            state: absent
            path: ./tmp_build/
      