- name: Setup Kubernetes
  hosts: localhost
  vars:
    kube_cpu: 4
    kube_memory: 24g
    kube_disk: 50G
    kube_profile: minikube
    kube_modules:
      - metrics-server
      #- dashboard
      - registry
      - ingress
      - ingress-dns
  tasks:
    - block:
        - name: Start Kubernetes Test Environment
          command: minikube start --profile={{ kube_profile }} --disk-size={{ kube_disk }} --cpus={{ kube_cpu }} --memory={{ kube_memory }} --container-runtime=cri-o --insecure-registry=\"192.168.0.0/16\"
        - name: Enable Addons
          command: "minikube --profile={{ kube_profile }} addons enable {{ item }}"
          with_items:
            - "{{ kube_modules }}"