- import_playbook: setup-kube.yaml
- name: Test Playbook
  hosts: localhost
  tasks:
    - block:
        - name: Create build directory
          file:
            path: ./tmp_build_java
            state: directory
        - name: Clone the repository
          ansible.builtin.git:
            repo: https://github.com/yohanswanepoel/ansible_apm_test.git
            dest: ./tmp_build_java
        - name: Create a k8s namespace
          kubernetes.core.k8s:
            api_version: v1
            kind: Namespace
            name: development
            state: present
        - name: Create a Deployment
          k8s:
            state: present      # State=present when you need to create new object
            namespace: development # defining the namespace
            src: ./tmp_build_java/java_app/petclinic_with_apm.yaml
            wait: yes
            wait_condition:
              type: Available
              status: True
              reason: MinimumReplicasAvailable
        - name: Create a Service
          k8s:
            state: present      # State=present when you need to create new object
            namespace: development # defining the namespace
            src: ./tmp_build_java/java_app/petclinic_service.yaml 
        - name: Set development namespace context
          command: kubectl config set-context --current --namespace=development
        - name: Get Nodeport IP Address
          command: minikube -p minikube ip
          register: test_ip
        - name: Get test url
          command: "kubectl get svc petclinic -n development -o go-template='http://{{ test_ip.stdout }}:{{ '{{' }}range.spec.ports{{ '}}' }}{{ '{{' }}if .nodePort{{ '}}' }}{{ '{{' }}.nodePort{{ '}}' }}{{ '{{' }}end{{ '}}' }}{{ '{{' }}end{{ '}}' }}'"
          register: test_url
        - name: Service URL for the petclinic
          debug:
            var: test_url.stdout
        - name: Run tests to generate APM traffic
          shell: export TEST_URL={{ test_url.stdout }}; pytest --otel-service-name='{{ lookup('env', 'OTEL_SERVICE_NAME') | default('Petclinic Test Environment', True) }}' --otel-session-name='Pet Clinic Test Cases' ./tmp_build_java/java_app/test_traffic.py 
        #- name: Get petclinic url
        #  command: "minikube --profile=apmtest service petclinic -n development"
        #  register: petclinic_url
        #- name: Display number of Services in the myapp namespace.
        #  debug:
        #    var: petclinic_url

      #rescue:
      #  - name: delete Minikube
      #    command: "minikube delete --profile={{ kube_profile }}"
      always:
        - name: Delete content & directory
          file:
            state: absent
            path: ./tmp_build_java/