apiVersion: v1 
kind: Service 
metadata: 
  name: skaffold-demo 
spec: 
  type: NodePort 
  ports: 
  - protocol: TCP 
    port: 8000 
    targetPort: 8000 
    nodePort: 30002 
  selector: 
    service: skaffold-demo