apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-demo
  template:
    metadata:
      labels:
        app: skaffold-demo
        service: skaffold-demo
    spec:
      dnsPolicy: ClusterFirstWithHostNet 
      restartPolicy: Always
      containers:
      - name: skaffold-demo
        image: localhost/skaffold-demo:latest
        ports:
        - containerPort: 8000
        
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        
        env: 
        - name: ELASTIC_APM_SERVER_URL 
          value: "http://host.minikube.internal:8200" 
        - name: ELASTIC_APM_SERVICE_NAME 
          value: "Accounts Demo" 