apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-demo
  template:
    metadata:
      labels:
        app: skaffold-demo
    spec:
      restartPolicy: Always
      containers:
      - name: skaffold-demo
        image: localhost/skaffold-demo:latest
        ports:
        - containerPort: 8000
        
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"